Values:
  maxCurrencyValue: 15
  minimumCurrencyValue: 5
  eloCurrencyMultiplier: 10
  defaultElo: 1250
  currencyChange: 1
  currencyName: "{0} Honour"
  killingSpree: 5
  shutdownMultiplier: 1
  shutdownMax: 5
  currencyOnJoin: yes